### ISSUE TITLE
Use either Yarn or npm

### ISSUE THREAD

**Issue by praseodym** [WISVCH/symposium-2020#21]
This repo currently has a Yarn `yarn.lock` file and an npm `package-lock.json` file; these lockfiles are not compatible. Also, both have been recently updated with conflicting changes.

The [`Dockerfile`](https://github.com/WISVCH/symposium-2020/blob/d7654d33909af55790f8302448d9f61c76e384fe/Dockerfile) currently uses Yarn, so I'd suggest only using Yarn. Alternatively, switch over to npm entirely, including the `Dockerfile`.

**Comment by KawinZheng** [comment]
That's right, we will do this issue next
