### ISSUE TITLE
SVG Logo not rendering properly

### ISSUE THREAD

**Issue by danielvangelder** [WISVCH/symposium-2020#23]
The logo of the symposium should render as follows:
![Good Logo](https://user-images.githubusercontent.com/23523444/81471276-4be99800-91f0-11ea-868b-78a79dfa0de0.png)

But currently, the SVG file renders in this way:
![Bad Logo](https://user-images.githubusercontent.com/23523444/81471321-a1be4000-91f0-11ea-8ad6-77afb37d3894.png)

The reason for this is that the browser does not recognize the required font (Amdale Mono). We have tried several approaches: defining the font within the SVG file but to no avail. It only works if the font is installed locally.

**Comment by svenvanhal** [comment]
This can be solved by outlining the characters (in Illustrator `Type → Create Outlines`)

**Comment by danielvangelder** [comment]
Will try! Thanks
